name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        php: ['8.0', '8.1']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup PHP
      uses: shivammathur/setup-php@2.19.0
      with:
        php-version: ${{ matrix.php }}
        tools: cs2pr
        coverage: xdebug

    - name: Setup problem matchers for PHPUnit
      run: echo '::add-matcher::${{ runner.tool_cache }}/phpunit.json'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ matrix.os }}-${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.php }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP CS Fixer
      run: composer run-script php-cs-fixer fix -- --dry-run --format=checkstyle | cs2pr

    - name: Run PHP_CodeSniffer
      run: composer run-script phpcs -- --report=checkstyle | cs2pr

    - name: Run PHPStan
      run: composer run-script phpstan

    - name: Run Psalm
      run: composer run-script psalm -- --output-format=github --shepherd

    - name: Run test suite
      run: composer run-script test -- --coverage-clover coverage.xml
      env:
        XDEBUG_MODE: coverage

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: ${{ matrix.os }}-${{ matrix.php }}
