name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        php: ['7.3', '7.4', '8.0']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: cs2pr
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2.1.5
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP_CodeSniffer
      run: composer run-script phpcs -- --report=checkstyle | cs2pr

    - name: Run PHPStan
      run: composer run-script phpstan

    - name: Run Psalm
      run: composer run-script psalm -- --output-format=github --shepherd

    - name: Run test suite
      run: composer run-script test -- --coverage-clover coverage.xml
      env:
        XDEBUG_MODE: coverage

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: ${{ matrix.os }}-${{ matrix.php }}
